sandtank-ml:
  app: trame-sandtank-ml
sandtank-xai:
  app: trame-sandtank-xai
mnist:
  app: trame-mnist
xaitk:
  app: xaitk-saliency-demo
visualizer:
  app: pv-visualizer
  cmd:
    - /opt/paraview/bin/pvpython
    - -m
    - paraview.apps.trame
    - --venv
    - /deploy/server/venv
    - --trame-app
    - pv_visualizer
    - --host
    - ${host}
    - --port
    - ${port}
    - --authKey
    - ${secret}
    - --server
    - --data
    - /data